package drone.tool;

import drone.tool.analytics.AnalyticsFrame;
import java.io.IOException;

/**
 * This panel is the ToolBar at the bottom of the application, it contains the
 * buttons to start the live broadcast and the analytics panel.
 *
 * @author Michea Colautti
 * @version 22.12.2021
 */
public class ToolBarPanel extends javax.swing.JPanel {

    Browser browser;

    /**
     * Creates new form ToolBarPanel.
     */
    public ToolBarPanel() {
        initComponents();
        browser = new Browser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 4, 50, 20));
        add(jPanel1);

        jButton1.setForeground(new java.awt.Color(242, 57, 6));
        jButton1.setText("Live");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);

        jButton2.setForeground(new java.awt.Color(204, 0, 204));
        jButton2.setText("Analytics");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);

        jLabel1.setText("Battery");
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Button for opening live.
     * 
     * @param evt the catched event, in this case click
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            browser.script();
            browser.openBrowser();
        } catch (IOException ex) {
            System.out.println("Errore apertura live");
            System.out.println(ex.getMessage());
        } catch (InterruptedException ex) {
            System.out.println("Errore browser");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Button for opening the analytics.
     * 
     * @param evt the catched event, in this case click
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AnalyticsFrame anayltics = new AnalyticsFrame();
        new Thread(anayltics).start();
        anayltics.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
